[package]
name = "lang-vm"
version = "0.1.0"
authors = ["nikhil.jain0987@gmail.com <nikhil.jain0987@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
